version: '3.8'

services:
  middleware:
    build: .
    ports:
      - "${MIDDLEWARE_PORT}:${MIDDLEWARE_PORT}"
    env_file:
      - .env
    volumes:
      - .:/app
    container_name: express-middleware